project_id = "kvgzaoiyyqxdqvyqdpfx"

[functions.submit-review]
verify_jwt = false

[functions.submit-blog]
verify_jwt = false

[functions.rate-blog]
verify_jwt = false

[functions.delete-blog]
verify_jwt = false

[functions.report-blog]
verify_jwt = false

[functions.moderate-blog]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false
